version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "quarterly"
    assignees:
      - "Breus"
    reviewers:
      - "Breus"
    groups:
      dependencies-gradle:
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    assignees:
      - "Breus"
    reviewers:
      - "Breus"
    labels:
      - "dependencies"
      - "automerge"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "deps"
    groups:
      dependencies-github-actions:
        patterns: ["*"]